### ISSUE TITLE
Include the user popup info of the filters to the viewer app

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#2]
_Item 2 in the 1/25/2019 action item list_

**Comment by makedadrake** [comment]
Please provide an update to this item.  Additional description of what viewer app and what popup is needed.  Is this for all viewer apps?  Is the user popup the same for all apps?

**Comment by talllguy** [comment]
@makedadrake remind me what the intent was here? Is it to provide a filter by username so you could audit a particular user's contributions?

**Comment by makedadrake** [comment]
I believe it was to add the user directions popup to the viewer assignment app. The viewer assignment app is not going to be completed.  Due to the small amount of people that that are using the assignment app.  Once there are no longer any changes a viewer app maybe required.  Lets make sure that any user popup information is on all remaining apps.

Makeda Drake PE
Project Manager, Transportation
[cid:image001.gif@01D4D975.CE41B240]<http://wbcm.com/>
Designing Infrastructure for Tomorrow ®
WHITNEY BAILEY COX & MAGNANI, LLC
300 East Joppa Road Suite 200 Baltimore, MD 21286
MAIN 410.512.4500 DIRECT 410.512.4636
[WBCM on LinkedIn]<https://www.linkedin.com/company/whitney-bailey-cox-&-magnani/>   [WBCM on Twitter] <https://twitter.com/wbcm_aec>    [WBCM on FaceBook] <https://www.facebook.com/WBCM.aec/>    [WBCM on Instagram] <https://www.instagram.com/wbcm_aec/>

**Comment by talllguy** [comment]
Streamlining the assign app and view app into one
