### ISSUE TITLE
Route Data issue in PG County

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#39]
Take note of how the speed limits are missing in the PG County area. Something amiss in the route dataset?

![Eqo27CodKg](https://user-images.githubusercontent.com/1827881/55987892-7de89d80-5c70-11e9-9abb-12f93305b99e.gif)

**Comment by johnshiu** [comment]
The speedlimit refresh hasn't been re-run in a while (it's not auto-run nightly because it takes forever), and IIRC, the PG inlets were added to production fairly recently. Right now, it is running the speedlimit refresh, so hopefully those speed limits will populate correctly after it's done. It could take several hours, however, and I'll update this ticket once it's ready.

**Comment by johnshiu** [comment]
The processing has completed; please try it again and let me know if it has been resolved.

**Comment by talllguy** [comment]
It is resolved now! Thanks.
