### ISSUE TITLE
Inlets and Pipes are not connecting on the map

### ISSUE THREAD

**Issue by talllguy** [kcigeospatial/Inlet-Field-and-Web-App-Configuration#40]
I'm pulling in the VPI_CONVEYANCE_RATING data for field reference along with the inlet data. When these features appear on the same map, they are slightly out of alignment. Could this be a projection issue?

![image](https://user-images.githubusercontent.com/1827881/56175855-fdef6a00-5fc6-11e9-9525-cd1b26b974e6.png)

Here's the service: https://maps.roads.maryland.gov/arcgis/rest/services/Inlet_Inspection/Inlet_ICP_PC_Status_View_Maryland_SHA/FeatureServer

**Comment by johnshiu** [comment]
I think this may be due to a mismatch in the domain resolution and tolerance settings. For the VPI_CONVEYANCE_RATING feature class, it is set at the default values for wkid 2248:

![image](https://user-images.githubusercontent.com/6249952/56176553-82db8300-5fc9-11e9-8af5-c91513fe6fab.png)

However, in NPDES, they use a custom resolution and tolerance:

![image](https://user-images.githubusercontent.com/6249952/56176520-5de71000-5fc9-11e9-9922-ec9d4778f7bb.png)

When we insert from NPDES.CONVEYANCE to FIELD.VPI_CONVEYANCE_RATING, we are probably losing resolution, which is why things are slightly off. For the ICP feature class, it already is set to the custom tolerances. 

To fix this, I have recreated the VPI_CONVEYANCE_RATING feature class and refreshed the data values. Please let me know if you continue to see mismatches in the data. I don't know if you'll need to recreate the MXD and republish to see the changes.

**Comment by talllguy** [comment]
@johnshiu perfect! No republishing needed: 
![image](https://user-images.githubusercontent.com/1827881/56177888-40687500-5fce-11e9-9a56-a9c1e1f8b5b0.png)
